services:
  wireguard:
    image: ${WG_IMAGE}
    ports:
      - "${WG_PORT}:${WG_PORT}/udp"
      - "${WG_UI_PORT}:${WG_UI_PORT}/tcp"
    environment:
      - PORT=${WG_UI_PORT}
      - WG_HOST=${WG_HOST}
      - WG_PORT=${WG_PORT}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS}
      - PASSWORD=${WG_PASSWORD}
    volumes:
      - ./wireguard:/etc/wireguard
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    logging:
      options:
        max-size: "10m"
        max-file: "3"
